Building for each release

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,29 +9,35 @@ echo "-----> Install ImageMagick"
 BUILD_DIR=$1
 CACHE_DIR=$2
 VENDOR_DIR="$BUILD_DIR/vendor"
-IMAGEMAGICK_TARBALL="ImageMagick-6.9.3-10.tar.gz"
-DOWNLOAD_URL="https://s3-us-west-2.amazonaws.com/autofi-cdn/$IMAGEMAGICK_TARBALL"
+INSTALL_DIR="$VENDOR_DIR/imagemagick"
 CACHE_FILE="$CACHE_DIR/imagemagick.tar.gz"
 
-if [ ! -f $CACHE_FILE ]; then
+# install imagemagick
+IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-6.9.3-10}"
+IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.gz"
+IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
+# SSL cert used on imagemagick not recognized by heroku.
+IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
 
-  cd $BUILD_DIR
-  # download image magick compiled binary (-O) silently (-s)
-  echo "-----> Downloading ImageMagick from $DOWNLOAD_URL"
-  wget $DOWNLOAD_URL -P $BUILD_DIR | indent
-  
-  # cache for future deploys
-  echo "-----> Caching ImageMagick installation"
-  mkdir -p $VENDOR_DIR
-  cd $VENDOR_DIR
-  mv $BUILD_DIR/$IMAGEMAGICK_TARBALL $CACHE_FILE
-  echo $CACHE_FILE
-  
+echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
+wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
+
+echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
+if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+  echo "Error: Unable to download ImageMagick" | indent
+  ls $BUILD_DIR | indent
+  exit 1;
 fi
+tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
 
-echo "-----> Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
-tar xzf $CACHE_FILE -C $VENDOR_DIR
-
+echo "-----> Building ImageMagick"
+cd $IMAGE_MAGICK_DIR
+export CPPFLAGS="-I$INSTALL_DIR/include"
+export LDFLAGS="-L$INSTALL_DIR/lib"
+./configure --prefix=$INSTALL_DIR
+make && make install
+cd ..
+rm -rf $IMAGE_MAGICK_DIR
 
 echo "-----> Writing policy file"
 mkdir -p $INSTALL_DIR/etc/ImageMagick
@@ -52,6 +58,59 @@ mkdir -p $(dirname $PROFILE_PATH)
 echo "export PATH=$ACTUAL_INSTALL_PATH/bin:\$PATH" >> $PROFILE_PATH
 echo "export LD_LIBRARY_PATH=$ACTUAL_INSTALL_PATH/lib:\$LD_LIBRARY_PATH" >> $PROFILE_PATH
 echo "export MAGICK_CONFIGURE_PATH=$ACTUAL_INSTALL_PATH" >> $PROFILE_PATH
+
+# indent() {
+#   sed -u 's/^/       /'
+# }
+
+# echo "-----> Install ImageMagick"
+
+# BUILD_DIR=$1
+# CACHE_DIR=$2
+# VENDOR_DIR="$BUILD_DIR/vendor"
+# IMAGEMAGICK_TARBALL="ImageMagick-6.9.3-10.tar.gz"
+# DOWNLOAD_URL="https://s3-us-west-2.amazonaws.com/autofi-cdn/$IMAGEMAGICK_TARBALL"
+# CACHE_FILE="$CACHE_DIR/imagemagick.tar.gz"
+
+# if [ ! -f $CACHE_FILE ]; then
+
+#   cd $BUILD_DIR
+#   # download image magick compiled binary (-O) silently (-s)
+#   echo "-----> Downloading ImageMagick from $DOWNLOAD_URL"
+#   wget $DOWNLOAD_URL -P $BUILD_DIR | indent
+  
+#   # cache for future deploys
+#   echo "-----> Caching ImageMagick installation"
+#   mkdir -p $VENDOR_DIR
+#   cd $VENDOR_DIR
+#   mv $BUILD_DIR/$IMAGEMAGICK_TARBALL $CACHE_FILE
+#   echo $CACHE_FILE
+  
+# fi
+
+# echo "-----> Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
+# tar xzf $CACHE_FILE -C $VENDOR_DIR
+
+
+# echo "-----> Writing policy file"
+# mkdir -p $INSTALL_DIR/etc/ImageMagick
+# cat > $INSTALL_DIR/policy.xml <<EOF
+# <policymap>
+#   <policy domain="coder" rights="none" pattern="EPHEMERAL" />
+#   <policy domain="coder" rights="none" pattern="HTTPS" />
+#   <policy domain="coder" rights="none" pattern="MVG" />
+#   <policy domain="coder" rights="none" pattern="MSL" />
+# </policymap>
+# EOF
+
+# # update PATH and LD_LIBRARY_PATH
+# echo "-----> Updating environment variables"
+# PROFILE_PATH="$BUILD_DIR/.profile.d/imagemagick.sh"
+# ACTUAL_INSTALL_PATH="$HOME/vendor/imagemagick"
+# mkdir -p $(dirname $PROFILE_PATH)
+# echo "export PATH=$ACTUAL_INSTALL_PATH/bin:\$PATH" >> $PROFILE_PATH
+# echo "export LD_LIBRARY_PATH=$ACTUAL_INSTALL_PATH/lib:\$LD_LIBRARY_PATH" >> $PROFILE_PATH
+# echo "export MAGICK_CONFIGURE_PATH=$ACTUAL_INSTALL_PATH" >> $PROFILE_PATH
 
 echo "--------------------------------"
 echo "IMAGE MAGICK VERSION:"
